<?php

namespace Nelmio\SlowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreeRepository extends EntityRepository
{
}